FROM ubuntu:16.04

# 2. Update system package manager

RUN apt-get update && apt-get full-upgrade -y

# 3. Installing python, pip, ssh

RUN apt-get install -y openssh-server python python-pip

# 4. Config public key

# 4.1. Make directory where ssh service socket will be.

RUN mkdir /var/run/sshd

# 4.2. Upload my public key to docker

COPY authorized_keys /root/.ssh/authorized_keys

# 4.3. Set permissions to public key.

RUN ["chmod","0600","/root/.ssh/authorized_keys"]

# 5. Expose ssh service

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
