---
- name: Create a app directory
  file:
    path: /opt/app
    state: directory

- name: Download app from github
  git:
    repo: 'git@github.com:AndresBena19/Store_inventory.git'
    dest: /opt/app/
    key_file: /opt/github_key
    accept_hostkey: yes  # '-o StrictHostKeyChecking=no'
    version: deploy_ver

- name: Create project virtualenv
  command: virtualenv -p python3.6 env
  args:
    chdir: /opt/app/

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: /opt/app/env

- name: Install app requirements.txt
  pip:
    requirements: /opt/app/Inventory/requirements.txt
    virtualenv: /opt/app/env
