---
- name: Install software-properties-common to can add repositories
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add ppa:deadsnakes/ppa repository to install python3.6
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    codename: xenial

- name: Installing python3.6, pip3, virtualenv and gunicorn
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - python3.6
      - python3-pip
      - virtualenv
      - git
      - gunicorn

- name: Configure locales to prevent locale misconfiguration error
  lineinfile:
    path: ~/.bashrc
    regexp: '^LC_ALL=C'
    line: 'LC_ALL=C'
    state: present
    insertafter: EOF

- name: Upload repository public key
  copy:
    src: files/github_key
    dest: /opt/
    mode: 0600
    owner: vagrant

#- name: Init ssh-agent
#  command: eval "$(ssh-agent -s)"

#- name: Add key to ssh-agent
#  command: ssh-add /opt/github_key
#  registry: verify

#- name: output
#  debug:
#    msg: "{{ verify }}"
